package timeline

import (
	"os"
	"path/filepath"
	"testing"
)

func TestWorktreeOfMainCheckout(t *testing.T) {
	root := t.TempDir()
	repo := filepath.Join(root, "myrepo")
	if err := os.MkdirAll(filepath.Join(repo, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	sub := filepath.Join(repo, "internal", "pkg")
	if err := os.MkdirAll(sub, 0o755); err != nil {
		t.Fatal(err)
	}

	got := worktreeOf(sub)
	if got.Repo != "myrepo" {
		t.Errorf("repo = %q, want myrepo", got.Repo)
	}
	if got.Name != "" {
		t.Errorf("name = %q, want empty for a main checkout", got.Name)
	}
}

func TestWorktreeOfLinkedWorktree(t *testing.T) {
	root := t.TempDir()
	repo := filepath.Join(root, "myrepo")
	if err := os.MkdirAll(filepath.Join(repo, ".git", "worktrees", "feature-x"), 0o755); err != nil {
		t.Fatal(err)
	}
	// A linked worktree checked out beside the repo, sharing its basename —
	// the case the cwd basename cannot tell apart from the main checkout.
	wt := filepath.Join(root, "wt", "myrepo")
	if err := os.MkdirAll(wt, 0o755); err != nil {
		t.Fatal(err)
	}
	gitdir := filepath.Join(repo, ".git", "worktrees", "feature-x")
	if err := os.WriteFile(filepath.Join(wt, ".git"), []byte("gitdir: "+gitdir+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	got := worktreeOf(wt)
	if got.Name != "feature-x" {
		t.Errorf("name = %q, want feature-x", got.Name)
	}
	if got.Repo != "myrepo" {
		t.Errorf("repo = %q, want myrepo", got.Repo)
	}
}

func TestWorktreeOfSubmodule(t *testing.T) {
	root := t.TempDir()
	repo := filepath.Join(root, "parent")
	if err := os.MkdirAll(filepath.Join(repo, ".git", "modules", "mod"), 0o755); err != nil {
		t.Fatal(err)
	}
	mod := filepath.Join(repo, "mod")
	if err := os.MkdirAll(mod, 0o755); err != nil {
		t.Fatal(err)
	}
	gitdir := filepath.Join(repo, ".git", "modules", "mod")
	if err := os.WriteFile(filepath.Join(mod, ".git"), []byte("gitdir: "+gitdir+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// A submodule is not a worktree: it gets no worktree name, and its repo is
	// its own directory rather than the parent's.
	got := worktreeOf(mod)
	if got.Name != "" {
		t.Errorf("name = %q, want empty for a submodule", got.Name)
	}
	if got.Repo != "mod" {
		t.Errorf("repo = %q, want mod", got.Repo)
	}
}

func TestWorktreeOfNoRepo(t *testing.T) {
	if got := worktreeOf(t.TempDir()); got != (Worktree{}) {
		t.Errorf("worktreeOf(non-repo) = %+v, want zero", got)
	}
}

func TestIsBoilerplateTitle(t *testing.T) {
	boilerplate := []string{
		"Caveat: The messages below were generated by the user while running local commands.",
		"<command-name>/compact</command-name>",
		"This session is being continued from a previous conversation",
	}
	for _, s := range boilerplate {
		if !isBoilerplateTitle(s) {
			t.Errorf("isBoilerplateTitle(%q) = false, want true", s[:30])
		}
	}
	real := []string{"Fix caffienate button not working", "", "Audit AI tool usage"}
	for _, s := range real {
		if isBoilerplateTitle(s) {
			t.Errorf("isBoilerplateTitle(%q) = true, want false", s)
		}
	}
}
